# Generated by Django 5.2.1 on 2025-05-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=50),
        ),
        migrations.AlterField(
            model_name='goals',
            name='title',
            field=models.CharField(default='Untitled Goal', max_length=50),
        ),
    ]
