# Generated by Django 5.2.1 on 2025-05-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
