# Generated by Django 5.2.1 on 2025-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0002_remove_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='bg_photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
