# Generated by Django 5.2.1 on 2025-05-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0002_tasks_title_alter_goals_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='No email provided', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
