# Generated by Django 5.2.1 on 2025-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0003_goal_bg_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='bg_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
